services:
  auth-api:
    build: ./Auth
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  submit-api:
    build: ./Submit
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
