version: "3.8"

services:
  auth:
    build:
      context: ./Auth
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  submit:
    build:
      context: ./Submit
      dockerfile: Dockerfile
    ports:
      - "5001:80"
