

services:
  auth-api:
    build:
      context: ./Auth
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend

  submit-api:
    build:
      context: ./Submit
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AUTH_API_URL=http://auth-api  # docker network-ში resolve-დება
    depends_on:
      - auth-api
    networks:
      - backend

networks:
  backend:
    driver: bridge
